### ISSUE TITLE
Метод containsGame() класса GameStore возвращает значение False вместо True

### ISSUE THREAD

**Issue by AVKretov** [natabask/javaqa-team-diplom#5]
# Описание
Тест метода shouldAddGame() (проверка добавления игры) не проходит.

# Локация дефекта
https://github.com/natabask/javaqa-team-diplom/blob/16bb785a4e33b27e975cd336bfc70c6bc289333a/src/test/java/ru/netology/GameStoreTest.java#L9

# Шаги воспроизведения

1.Открыть [код программы](https://github.com/natabask/javaqa-team-diplom) в IDEA
2.Запустить тест shouldAddGame() класса GameStore
*Ожидаемый результат:* Тест shouldAddGame проходит успешно. В логе отсутствуют ошибки
*Фактический результат:* Тест shouldAddGame() падает с ошибкой: org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false

# Скриншот
![image](![log1](https://user-images.githubusercontent.com/81714303/160823217-636b72f2-b8ca-4a0e-a4c1-a123c9c1b1b7.png)

# Окружение
* **Операционная система:** Win 10 19042.1466
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by natabask** [comment]
Ошибка исправлена в [коммите](https://github.com/natabask/javaqa-team-diplom/commit/a4126a13c7f12f3c5c6a3212e9ff5671bbedf045)
