### ISSUE TITLE
Метод addPlayTime не суммирует значение времени 

### ISSUE THREAD

**Issue by AVKretov** [natabask/javaqa-team-diplom#7]
# Описание
Тест метода addPlayTime(Условие : Время должно суммироваться с прошлым значением для этого игрока) падает
![Screenshot2](https://user-images.githubusercontent.com/81714303/160839456-125cb40e-6c5d-45b4-a15d-ee256c7ad191.png)

# Локация дефекта
https://github.com/natabask/javaqa-team-diplom/blob/682a06ad5b795d2f5a2b3fcd8306596675af0999/src/main/java/ru/netology/GameStore.java#L48

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/natabask/javaqa-team-diplom) в IDEA
2. Запустить тест shouldSummPlayerTime() класса GameStoreTest

*Ожидаемый результат:* Тест shouldSummPlayerTime(проходит успешно.
*Фактический результат:* Тест shouldSummPlayerTime(падает с ошибкой: org.opentest4j.AssertionFailedError: 
Expected :Vasiliy
Actual   :Genadiy

# Скриншот
![log3](https://user-images.githubusercontent.com/81714303/160840113-9d47839c-85b5-47ea-a0dd-69429822404e.png)

# Окружение
* **Операционная система:** Win 10 19042.1466
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by natabask** [comment]
Ошибка в методе addPlayTime исправлена в [коммите](https://github.com/natabask/javaqa-team-diplom/commit/ecf9a909b977830ee6dbfcccc15a64128e4eb314)
